# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-01-11 13:52
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DateState',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(verbose_name='Fecha de Inicio')),
                ('finish_date', models.DateField(verbose_name='Fecha de Conclusi\xf3n')),
            ],
        ),
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_email', models.EmailField(max_length=254, verbose_name='E-Mail')),
                ('description', models.TextField(verbose_name='Descripci\xf3n')),
                ('name', models.CharField(max_length=200, verbose_name='Nombre')),
                ('url', models.URLField(verbose_name='URL')),
            ],
        ),
        migrations.CreateModel(
            name='Inscription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mozilla_subvention_description', models.TextField(verbose_name='Mozilla Descripci\xf3n Propuesta')),
                ('payed', models.BooleanField(default=False, verbose_name='\xbfPagado?')),
                ('not_registered', models.BooleanField(default=False, verbose_name='No aprobado')),
                ('registered', models.BooleanField(default=False, verbose_name='Aprobado')),
                ('subvention_request', models.BooleanField(default=False, verbose_name='\xbfPropuesta Enviada?')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
        ),
        migrations.CreateModel(
            name='Matriculado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avisado', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Patrocinadores',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre')),
                ('web', models.URLField(verbose_name='Web')),
                ('logo', models.ImageField(upload_to='logos/', verbose_name='logo')),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nombre')),
                ('last_name', models.CharField(max_length=255, verbose_name='Apellido')),
                ('institution', models.CharField(max_length=12, verbose_name='Instituci\xf3n')),
                ('alimentary_restriction', models.TextField(null=True, verbose_name='Restrinci\xf3n Alimentaria')),
                ('born_date', models.DateField(verbose_name='Fecha de Nacimiento')),
                ('gender', models.CharField(choices=[('M', 'Masculino'), ('F', 'Femenino')], max_length=1, verbose_name='Genero')),
                ('health_consideration', models.TextField(null=True, verbose_name='Condiciones de Salud')),
                ('identification', models.CharField(max_length=12, null=True, verbose_name='Identificaci\xf3n')),
                ('nationality', models.CharField(max_length=12, verbose_name='Nacionalidad')),
                ('snore', models.BooleanField(default=False, verbose_name='\xbfRonca?')),
                ('enrolled', models.BooleanField(default=False, verbose_name='\xbfMatriculado?')),
                ('entry_country', models.IntegerField(null=True, verbose_name='Entradas del Pa\xeds')),
                ('out_country', models.IntegerField(null=True, verbose_name='Salidas del Pa\xeds')),
                ('entry_port', models.CharField(max_length=100, null=True, verbose_name='Puerto de Entrada')),
                ('out_port', models.CharField(max_length=100, null=True, verbose_name='Puerto de Salida')),
                ('entry_country_date', models.DateField(null=True, verbose_name='Fecha de Entrada al pa\xeds')),
                ('out_country_date', models.DateField(null=True, verbose_name='Fecha de Salida del pa\xeds')),
                ('letter', models.TextField(null=True, verbose_name='Carta Migratoria')),
                ('invitation_file', models.BooleanField(default=False, verbose_name='\xbfEmail de Invitaci\xf3n?')),
                ('diploma', models.BooleanField(default=False, verbose_name='\xbfEmail de Diploma?')),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.TextField(verbose_name='Respuestas')),
                ('created', models.DateField(auto_now_add=True, verbose_name='Fecha de Creaci\xf3n')),
                ('published', models.BooleanField(verbose_name='\xbfPublicado?')),
                ('question', models.TextField(verbose_name='Pregunta')),
            ],
        ),
        migrations.CreateModel(
            name='QuestionCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emoji_alt', models.CharField(max_length=50, verbose_name='Emoji')),
                ('name', models.CharField(max_length=100, verbose_name='Categor\xeda')),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('available_beds', models.SmallIntegerField(verbose_name='Camas Disponibles')),
                ('coin', models.CharField(max_length=100, verbose_name='Moneda')),
                ('floor', models.SmallIntegerField(verbose_name='Piso')),
                ('matrimonial', models.BooleanField(verbose_name='Matrimonial')),
                ('number', models.CharField(max_length=50, verbose_name='N\xfamero')),
                ('price_per_bed', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Precio de la Cama')),
                ('total_beds', models.SmallIntegerField(verbose_name='Total de Camas')),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='system.Hotel', verbose_name='Hotel')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
        ),
        migrations.CreateModel(
            name='Speech',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('audience', models.CharField(choices=[('PG', 'P\xfablico General'), ('NB', 'Nivel Basico'), ('NI', 'Nivel Intermedio'), ('NA', 'Nivel Avanzado'), ('PRO', 'Profesional')], max_length=45, verbose_name='P\xfablico')),
                ('description', models.TextField(verbose_name='Descripci\xf3n')),
                ('notes', models.TextField(verbose_name='Notas')),
                ('skill_level', models.PositiveIntegerField(verbose_name='Nivel de Habilidad')),
                ('speaker_information', models.TextField(verbose_name='Informaci\xf3n del Autor')),
                ('title', models.CharField(max_length=250, verbose_name='T\xedtulo')),
                ('places', models.CharField(max_length=250, null=True, verbose_name='Lugares')),
                ('pepe', models.DateTimeField(null=True, verbose_name='Fecha del Evento')),
                ('slug', models.SlugField(help_text='Generador de url, se recomienda no modificar', max_length=255, unique=True)),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creado')),
                ('published', models.BooleanField(default=False, verbose_name='\xbfPublicado?')),
            ],
            options={
                'ordering': ['date_created'],
            },
        ),
        migrations.CreateModel(
            name='SpeechResource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recurso', models.FileField(upload_to='recursos/')),
                ('speech', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recursos', to='system.Speech')),
            ],
        ),
        migrations.CreateModel(
            name='SpeechType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('Talleres', 'Talleres'), ('Charlas', 'Charlas'), ('Di\xe1logos', 'Di\xe1logos')], max_length=45, verbose_name='Nombre')),
                ('icons', models.CharField(choices=[('/static/img/talleres.png', 'Talleres'), ('/static/img/charlas.png', 'Charlas'), ('/static/img/dialogos.png', 'Di\xe1logos')], max_length=45, verbose_name='Iconos')),
                ('slug', models.SlugField(help_text='Generador de url, se recomienda no modificar', unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=45, unique=True, verbose_name='Nombre')),
                ('description', models.TextField(verbose_name='Descripci\xf3n')),
                ('slug', models.SlugField(help_text='Generador de url, se recomienda no modificar', unique=True)),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creado')),
            ],
            options={
                'ordering': ['-date_created'],
            },
        ),
        migrations.CreateModel(
            name='Tshirt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.PositiveIntegerField(verbose_name='Cantidad')),
                ('last_update', models.DateField(verbose_name='\xdaltima Actualizaci\xf3n')),
                ('size', models.CharField(max_length=15, verbose_name='Talla')),
                ('pagada', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='TshirtStyle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(verbose_name='Descripci\xf3n')),
                ('gender', models.CharField(choices=[('M', 'Masculino'), ('F', 'Femenino')], max_length=1, verbose_name='G\xe9nero')),
                ('img1', models.ImageField(upload_to='Tshirt/', verbose_name='Imagen 1')),
                ('img2', models.ImageField(upload_to='Tshirt/', verbose_name='Imagen 2')),
                ('img3', models.ImageField(upload_to='Tshirt/', verbose_name='Imagen 3')),
                ('name', models.CharField(max_length=45, verbose_name='Nombre')),
                ('price', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Precio')),
            ],
        ),
        migrations.AddField(
            model_name='tshirt',
            name='style',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='system.TshirtStyle', verbose_name='Estilo'),
        ),
        migrations.AddField(
            model_name='tshirt',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario'),
        ),
        migrations.AddField(
            model_name='speech',
            name='speech_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='system.SpeechType', verbose_name='Tipo de Actividad'),
        ),
        migrations.AddField(
            model_name='speech',
            name='topic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='system.Topic', verbose_name='Tema'),
        ),
        migrations.AddField(
            model_name='speech',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='speechs', to=settings.AUTH_USER_MODEL, verbose_name='Usuario'),
        ),
        migrations.AddField(
            model_name='question',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='system.QuestionCategory'),
        ),
        migrations.AddField(
            model_name='profile',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='profile_speech_likes', to='system.Speech'),
        ),
        migrations.AddField(
            model_name='profile',
            name='matriculatedspeechs',
            field=models.ManyToManyField(blank=True, to='system.Speech'),
        ),
        migrations.AddField(
            model_name='profile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario'),
        ),
        migrations.AddField(
            model_name='matriculado',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='system.Profile'),
        ),
        migrations.AddField(
            model_name='matriculado',
            name='speech',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='system.Speech'),
        ),
    ]
