# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-12-21 18:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='speech',
            options={'ordering': ['date_created']},
        ),
        migrations.AlterModelOptions(
            name='topic',
            options={'ordering': ['-date_created']},
        ),
        migrations.AddField(
            model_name='speech',
            name='published',
            field=models.BooleanField(default=True, verbose_name='Published'),
            preserve_default=False,
        ),
    ]
