# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-12-11 16:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='entry_country',
            field=models.IntegerField(verbose_name='Entry and out from country'),
        ),
    ]
