# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-01-07 23:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='speech',
            name='slug',
            field=models.SlugField(help_text='Generador de url, se recomienda no modificar', max_length=255, unique=True),
        ),
    ]
