# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-12-14 11:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='speechtype',
            name='name',
            field=models.CharField(choices=[('Talleres', 'T'), ('Charlas', 'CH'), ('Dialogos', 'D')], max_length=45, verbose_name='Name'),
        ),
    ]
