# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-01-07 15:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='speech',
            name='date_start',
        ),
    ]
