# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-01-11 00:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='entry_country_date',
            field=models.DateField(null=True, verbose_name='Fecha de Entrada al pa\xeds'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='out_country_date',
            field=models.DateField(null=True, verbose_name='Fecha de Salida del pa\xeds'),
        ),
    ]
