# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-12-21 23:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0002_auto_20161222_0009'),
    ]

    operations = [
        migrations.AlterField(
            model_name='speech',
            name='days',
            field=models.DateTimeField(verbose_name='Event Start'),
        ),
    ]
