# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-12-09 11:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0002_datestate'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='enrolled',
            field=models.BooleanField(default=False, verbose_name='Enrolled?'),
            preserve_default=False,
        ),
    ]
