# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-12-19 17:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0002_auto_20161219_1744'),
    ]

    operations = [
        migrations.RenameField(
            model_name='speech',
            old_name='tag',
            new_name='slug',
        ),
    ]
