# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-12-21 18:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0002_auto_20161221_1924'),
    ]

    operations = [
        migrations.AlterField(
            model_name='speech',
            name='published',
            field=models.BooleanField(default=False, verbose_name='Published'),
        ),
    ]
