# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-12-23 10:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0002_auto_20161223_1101'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tshirtstyle',
            name='img1',
            field=models.ImageField(upload_to='/media/Tshirt/', verbose_name='Image 1'),
        ),
        migrations.AlterField(
            model_name='tshirtstyle',
            name='img2',
            field=models.ImageField(upload_to='/media/Tshirt/', verbose_name='Image 2'),
        ),
        migrations.AlterField(
            model_name='tshirtstyle',
            name='img3',
            field=models.ImageField(upload_to='/media/Tshirt/', verbose_name='Image 3'),
        ),
    ]
