# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-01-07 17:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0002_remove_speech_date_start'),
    ]

    operations = [
        migrations.RenameField(
            model_name='speech',
            old_name='days',
            new_name='pepe',
        ),
    ]
