# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-12-23 11:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0003_auto_20161223_1140'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tshirtstyle',
            name='img1',
            field=models.ImageField(upload_to='media/Tshirt/', verbose_name='Image 1'),
        ),
        migrations.AlterField(
            model_name='tshirtstyle',
            name='img2',
            field=models.ImageField(upload_to='media/Tshirt/', verbose_name='Image 2'),
        ),
        migrations.AlterField(
            model_name='tshirtstyle',
            name='img3',
            field=models.ImageField(upload_to='media/Tshirt/', verbose_name='Image 3'),
        ),
    ]
