# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-12-21 23:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0003_auto_20161222_0009'),
    ]

    operations = [
        migrations.AlterField(
            model_name='speech',
            name='days',
            field=models.DateTimeField(null=True, verbose_name='Event Start'),
        ),
        migrations.AlterField(
            model_name='speech',
            name='places',
            field=models.CharField(max_length=250, null=True, verbose_name='Places'),
        ),
    ]
