# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-12-09 14:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0004_auto_20161209_1259'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_email', models.EmailField(max_length=254, verbose_name='E-Mail')),
                ('description', models.TextField(verbose_name='Description')),
                ('name', models.CharField(max_length=200, verbose_name='Name')),
                ('url', models.URLField(verbose_name='URL')),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.TextField(verbose_name='Answer')),
                ('created', models.DateField(verbose_name='Date Created')),
                ('published', models.BooleanField(verbose_name='Published')),
                ('question', models.TextField(verbose_name='Question')),
            ],
        ),
        migrations.CreateModel(
            name='QuestionCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emoji_alt', models.CharField(max_length=50, verbose_name='Emoji')),
                ('name', models.CharField(max_length=100, verbose_name='Category')),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('available_beds', models.SmallIntegerField(verbose_name='Available Beds')),
                ('coin', models.CharField(max_length=100, verbose_name='Coin')),
                ('floor', models.SmallIntegerField(verbose_name='Floor')),
                ('matrimonial', models.BooleanField(verbose_name='Matrimonial')),
                ('number', models.CharField(max_length=50, verbose_name='Number')),
                ('price_per_bed', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Bed`s Prices')),
                ('total_beds', models.SmallIntegerField(verbose_name='Total Beds')),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='system.Hotel', verbose_name='Hotel')),
            ],
        ),
        migrations.AddField(
            model_name='question',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='system.QuestionCategory'),
        ),
    ]
