# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-12-21 23:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0004_auto_20161222_0044'),
    ]

    operations = [
        migrations.AlterField(
            model_name='speech',
            name='date_start',
            field=models.DateTimeField(default='2016-01-01', verbose_name='Start Date'),
        ),
    ]
