# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-12-21 23:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0005_auto_20161222_0051'),
    ]

    operations = [
        migrations.AlterField(
            model_name='speech',
            name='date_start',
            field=models.DateTimeField(null=True, verbose_name='Start Date'),
        ),
    ]
